# Generated by Django 6.1.1 on 2026-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='correo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='sinemail@correo.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
